server:
  port: 5000

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          client-authorization-code:
            provider: server
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:5000/authorized"
            scope: message.read,message.write
            client-name: client-authorization-code
        provider:
          server:
            issuer-uri: http://127.0.0.1:4000